import { themes as prismThemes } from "prism-react-renderer";
import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";
import type { ScalarOptions } from "@scalar/docusaurus";
import path from "path";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Load API configuration (generated by update-api-urls.js script)
let apiConfig = {
  developmentApiUrl:
    "https://raw.githubusercontent.com/owncast/owncast/refs/heads/develop/openapi.yaml",
  releaseApiUrl:
    "https://raw.githubusercontent.com/owncast/owncast/refs/heads/master/openapi.yaml",
};

try {
  apiConfig = require("./api-config.json");
} catch (error) {
  console.warn("Could not load api-config.json, using defaults");
}

// All redirect configurations - both wildcards and regular redirects
const ALL_REDIRECTS = [
  // Wildcard redirects
  {
    to: "/docs/troubleshoot/*",
    from: "/troubleshoot/*",
    excludePaths: ["/troubleshoot/"],
  },
  // {
  //   to: "/docs/troubleshooting/*",
  //   from: "/troubleshoot/*",
  //   excludePaths: ["/troubleshoot/"],
  // },
  { to: "/docs/api/*", from: "/thirdparty/*" },
  { to: "/docs/getting-started/install/providers/*", from: "/quickstart/*" },

  // Regular redirects
  { to: "/docs/getting-started/install", from: "/install" },
  { to: "/docs/getting-started/install", from: "/installation" },
  { to: "/docs/getting-started/install", from: "/docs/install" },
  { to: "/docs/getting-started/install", from: "/docs/installation" },
  { to: "/quickstart", from: "/docs/quickstart" },
  { to: "/docs/getting-started/install", from: "/quickstart/installation" },
  {
    to: "/docs/getting-started/install/installer",
    from: "/quickstart/installer",
  },
  { to: "/docs/getting-started/install/manual", from: "/quickstart/manual" },
  {
    to: "/docs/getting-started/configure-first-stream",
    from: "/quickstart/nextsteps",
  },
  {
    to: "/docs/getting-started/install/providers",
    from: "/quickstart/providers",
  },
  { to: "/docs/watching-streams", from: "/docs/watching-on-tvs" },
  {
    to: "/docs/getting-started/install/container",
    from: "/quickstart/container",
  },
  { to: "/docs/getting-started/install/container", from: "/quickstart/docker" },
  {
    to: "/docs/getting-started/configure-first-stream",
    from: "/quickstart/configure",
  },
  { to: "/docs/storage", from: "/docs/s3/" },
  { to: "/docs/viewers", from: "/docs/geoip/" },
  { to: "/docs/video", from: "/docs/encoding/" },
  { to: "/docs/chat/moderation", from: "/docs/moderation/" },
  { to: "/docs/chat/chat-authentication", from: "/docs/chat-authentication" },
  { to: "/contribute", from: "/help" },
];

const config: Config = {
  title: "Owncast",
  tagline: "Free and Open Source Livestreaming",
  favicon: "/favicon.png",

  // Static scripts (loaded outside of webpack/React)
  scripts: [
    {
      src: "/js/expand-get-started.js",
      async: true,
    },
  ],

  markdown: {
    hooks: {
      onBrokenMarkdownImages: "warn",
    },
    mermaid: true,
  },

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  // Set the production url of your site here
  url: "https://owncast.online",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/",

  // GitHub pages deployment config.
  organizationName: "owncast", // Usually your GitHub org/user name.
  projectName: "owncast.github.io", // Usually your repo name.

  onBrokenLinks: "warn",

  i18n: {
    defaultLocale: "en",
    locales: ["en", "es", "fr", "de"],
    localeConfigs: {
      en: {
        label: "English",
        htmlLang: "en-US",
      },
      es: {
        label: "Español",
        htmlLang: "es",
      },
      fr: {
        label: "Français",
        htmlLang: "fr",
      },
      de: {
        label: "Deutsch",
        htmlLang: "de",
      },
    },
  },

  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath: "./sidebars.ts",
          routeBasePath: "docs",
          path: "docs",
          // Enable edit URLs to allow contributors to edit documentation on GitHub
          editUrl:
            "https://github.com/owncast/owncast.github.io/edit/owncast-docusaurus/",
          // docItemComponent: "@theme/ApiItem", // Derived from docusaurus-theme-openapi
        },
        blog: false, // Disabled - using multi-instance blog plugins instead
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  themes: ["@docusaurus/theme-mermaid"],

  plugins: [
    // Releases blog - for version releases
    [
      "@docusaurus/plugin-content-blog",
      {
        id: "releases",
        routeBasePath: "releases",
        path: "./releases",
        blogTitle: "Owncast Releases",
        blogDescription: "Version releases and changelogs for Owncast",
        showReadingTime: true,
        postsPerPage: 10,
        feedOptions: {
          type: ["rss", "atom"],
          title: "Owncast Releases",
          description: "Version releases and changelogs for Owncast",
          copyright: `Copyright © ${new Date().getFullYear()} Owncast`,
          language: "en-US",
          limit: 20,
          xslt: true,
        },
        onInlineTags: "warn",
        onInlineAuthors: "warn",
        onUntruncatedBlogPosts: "ignore",
      },
    ],
    // News blog - for announcements, updates, and general news
    [
      "@docusaurus/plugin-content-blog",
      {
        id: "news",
        routeBasePath: "news",
        path: "./news",
        blogTitle: "Owncast News",
        blogDescription:
          "Announcements, updates, and news from the Owncast project",
        showReadingTime: true,
        postsPerPage: 10,
        feedOptions: {
          type: ["rss", "atom"],
          title: "Owncast News",
          description:
            "Announcements, updates, and news from the Owncast project",
          copyright: `Copyright © ${new Date().getFullYear()} Owncast`,
          language: "en-US",
          limit: 20,
          xslt: true,
        },
        onInlineTags: "warn",
        onInlineAuthors: "warn",
        onUntruncatedBlogPosts: "ignore",
      },
    ],
    // Custom plugin to support @/ path alias for imports
    function webpackAliasPlugin() {
      return {
        name: "webpack-alias-plugin",
        configureWebpack() {
          return {
            resolve: {
              alias: {
                "@": path.resolve(__dirname, "src"),
              },
            },
          };
        },
      };
    },
    [
      "@docusaurus/plugin-client-redirects",
      {
        createRedirects(existingPath: string) {
          const redirects: string[] = [];

          // Process ALL wildcard redirects generically
          for (const config of ALL_REDIRECTS) {
            const { to, from, excludePaths = [] } = config;

            // Only process entries that have wildcards in both to and from
            if (to.includes("*") && from.includes("*")) {
              const toPrefix = to.replace("*", "");
              const fromPrefix = from.replace("*", "");

              // If existing path matches the "to" pattern, create redirect from "from" pattern
              if (existingPath.startsWith(toPrefix)) {
                const suffix = existingPath.substring(toPrefix.length);
                const oldPath = fromPrefix + suffix;

                // Skip excluded paths
                if (excludePaths.includes(oldPath)) {
                  continue;
                }

                // Skip if the redirect source would be the base path without suffix
                if (oldPath === fromPrefix.replace("*", "")) {
                  continue;
                }

                redirects.push(oldPath);
              }
            }
          }

          return redirects.length > 0 ? redirects : undefined;
        },
        redirects: ALL_REDIRECTS.filter((r) => !r.to.includes("*")), // Only non-wildcard redirects
      },
    ],
    [
      "@easyops-cn/docusaurus-search-local",
      {
        hashed: true,
        language: ["en"],
        highlightSearchTermsOnTargetPage: true,
        explicitSearchResultPath: true,
        blogDir: ["releases", "news"],
      },
    ],
    [
      require.resolve("./plugins/related-docs"),
      {
        pluginId: "related-docs",
        docsPath: "docs",
        routeBasePath: "docs",
        maxRelated: 6,

        // Scoring knobs (good defaults below)
        tfidfWeight: 1.0,
        tagWeight: 0.6,
        headingWeight: 0.4,
        sameSectionBoost: 0.15,
        minScore: 0.06,
      },
    ],
    [
      require.resolve("./plugins/github-info"),
      {
        owner: "owncast",
        repo: "owncast",
      },
    ],
    [
      require.resolve("./plugins/milestones-plugin"),
      {
        owner: "owncast",
        repo: "owncast",
        milestones: [28, 5, 23, 20, 31], // Milestone numbers to fetch
      },
    ],
    [
      "@scalar/docusaurus",
      {
        id: "api-development",
        label: "Owncast Web APIs (Development)",
        route: "/api/development",
        showNavLink: false, // optional, default is true
        configuration: {
          url: apiConfig.developmentApiUrl,
        },
      } as ScalarOptions,
    ],
    [
      "@scalar/docusaurus",
      {
        id: "api-release",
        label: "Owncast Web APIs (Release)",
        route: "/api/release",
        showNavLink: false, // optional, default is true
        configuration: {
          url: apiConfig.releaseApiUrl,
        },
      } as ScalarOptions,
    ],
  ],

  themeConfig: {
    // Replace with your project's social card
    image: "img/owncast-logo-1000x1000.png",
    metadata: [
      {
        name: "description",
        content:
          "Owncast is a free and open source live video and web chat server for use with existing broadcasting software. Point your live stream at a Owncast server you personally control and regain ownership over your content.",
      },
      {
        name: "keywords",
        content:
          "live streaming, live video, open source, self-hosted, streaming server, rtmp, hls, chat",
      },
      { name: "twitter:site", content: "@owncastlive" },
      { name: "twitter:creator", content: "@owncastlive" },
      { property: "og:locale", content: "en_US" },
      { property: "og:type", content: "website" },
    ],
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: "Owncast",
      logo: {
        alt: "Owncast Logo",
        src: "images/logo-white.svg",
        // srcDark: "images/logo-white.svg",
      },
      items: [
        {
          to: "/docs/",
          position: "left",
          label: "Documentation",
        },
        {
          to: "/releases",
          label: "Releases",
          position: "left",
        },
        {
          to: "/troubleshoot",
          label: "Troubleshooting",
          position: "left",
        },
        {
          to: "/quickstart",
          label: "Quickstart",
          position: "left",
        },
        {
          type: "localeDropdown",
          position: "right",
        },
        {
          href: "https://github.com/owncast",
          position: "right",
          className: "header-github-link",
          "aria-label": "GitHub repository",
        },
        {
          href: "https://app.element.io/#/room/#owncast.support:matrix.org",
          position: "right",
          className: "header-matrix-link",
          "aria-label": "Matrix chat",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Getting Started",
          items: [
            {
              label: "Documentation",
              to: "/docs/",
            },
            {
              label: "Quick Start",
              to: "/quickstart",
            },
            {
              to: "/releases",
              label: "Releases",
            },
          ],
        },
        {
          title: "Community",
          items: [
            {
              label: "GitHub",
              href: "https://github.com/owncast",
            },
            {
              label: "Community Chat",
              href: "https://app.element.io/#/room/#owncast.support:matrix.org",
            },
            {
              label: "Contribute",
              href: "/contribute",
            },
            {
              label: "Donate",
              href: "https://opencollective.com/owncast/donate",
            },
            {
              label: "Contact",
              href: "/contact",
            },
          ],
        },
        {
          title: "More",
          items: [
            {
              label: "Demo Server",
              href: "https://watch.owncast.online",
            },
            {
              label: "Merch store",
              href: "https://merch.owncast.online",
            },
            {
              label: "Roadmap",
              to: "/roadmap",
            },
          ],
        },
      ],
      copyright:
        'Owncast® is a <a href="/trademark">registered trademark</a> of the Owncast Project.',
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: [
        "bash",
        "diff",
        "json",
        "yaml",
        "toml",
        "javascript",
        "nginx",
        "apacheconf",
      ],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
