import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docs: [
    {
      type: "doc",
      id: "index",
      label: "Owncast Documentation",
    },
    {
      type: "category",
      label: "Get started",
      className: "get-started-category",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Install Owncast",
          items: [
            "getting-started/install/installer",
            "getting-started/install/manual",
            "getting-started/install/container",
            "getting-started/install/providers",
          ],
        },
        "resources-requirements",
        "getting-started/configure-first-stream",
      ],
    },
    {
      type: "category",
      label: "Configure your Owncast server",
      items: [
        "configuration/index",
        "configuration/website",
        "embed",
        "configuration/appearance",
        "configuration/custom-javascript",
        "configuration/plugins",
        "configuration/notifications",
        "configuration/systemservice",
      ],
    },
    {
      type: "category",
      label: "Configure video quality & performance",
      items: [
        {
          type: "category",
          label: "Setup your broadcasting software",
          items: [
            {
              type: "autogenerated",
              dirName: "broadcasting",
            },
          ],
        },
        "video",
        "storage",
        "latency",
        "metrics",
      ],
    },
    {
      type: "category",
      label: "Customize chat features",
      items: [
        {
          type: "autogenerated",
          dirName: "chat",
        },
      ],
    },
    {
      type: "category",
      label: "Increase social reach and engagement",
      items: [
        {
          type: "autogenerated",
          dirName: "social",
        },
      ],
    },
    {
      type: "category",
      label: "Plugins, APIs, webhooks & your custom functionality",
      items: [
        {
          type: "category",
          label: "Web APIs",
          items: [
            "api/apis",
            "api/webhooks",
            {
              type: "category",
              label: "API Reference",
              items: [
                {
                  type: "link",
                  label: "In development API documentation",
                  href: "/api/development",
                },
                {
                  type: "link",
                  label: "Released API documentation",
                  href: "/api/release",
                },
              ],
            },
          ],
        },
        "api/activitypub",
        {
          type: "category",
          label: "Owncast plugins",
          items: [
            "plugins/index",
            {
              type: "category",
              label: "Get started",
              key: "plugins-get-started",
              items: [
                "plugins/quickstart",
                {
                  type: "autogenerated",
                  dirName: "plugins/sdks",
                },
              ],
            },
            {
              type: "category",
              label: "Build features",
              items: [
                "plugins/chat",
                "plugins/commands",
                "plugins/auth",
                "plugins/http",
                "plugins/ui",
              ],
            },
            {
              type: "category",
              label: "Reference",
              items: [
                "plugins/manifest",
                "plugins/events",
                "plugins/apis",
                "plugins/permissions",
              ],
            },
            {
              type: "category",
              label: "Ship & test",
              items: ["plugins/packaging", "plugins/testing"],
            },
          ],
        },
        "api/actions",
      ],
    },
    {
      type: "category",
      label: "Optional / Advanced Features & Maintenance",
      items: [
        {
          type: "category",
          label: "Add SSL & reverse proxies",
          items: [
            {
              type: "autogenerated",
              dirName: "sslproxies",
            },
          ],
        },
        "codecs",
        "cdns",
        "backups",
        "configuration/runtime-flags",
        "scaling",
        "viewers",
        "custom-assets",
      ],
    },
    {
      type: "category",
      label: "Watching Owncast Streams",
      items: [
        {
          type: "autogenerated",
          dirName: "watching-streams",
        },
      ],
    },
    "directory",
  ],
};

export default sidebars;
