import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docs: [
    {
      type: "doc",
      id: "index",
      label: "Owncast Documentation",
    },
    {
      type: "category",
      label: "Get started",
      link: { type: "doc", id: "getting-started/install/index" },
      className: "get-started-category",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Install Owncast",
          link: { type: "doc", id: "getting-started/install/index" },
          items: [
            "getting-started/install/installer",
            "getting-started/install/manual",
            "getting-started/install/container",
            "getting-started/install/providers",
          ],
        },
        "resources-requirements",
        "getting-started/configure-first-stream",
      ],
    },
    {
      type: "category",
      label: "Configure your Owncast server",
      link: { type: "doc", id: "configuration/index" },
      items: [
        "configuration/website",
        "embed",
        "configuration/appearance",
        "configuration/custom-javascript",
        "configuration/plugins",
        "configuration/notifications",
        "configuration/systemservice",
      ],
    },
    {
      type: "category",
      label: "Configure video quality & performance",
      link: { type: "doc", id: "video-performance" },
      items: [
        {
          type: "category",
          label: "Setup your broadcasting software",
          link: { type: "doc", id: "broadcasting/index" },
          items: [
            "broadcasting/obs",
            "broadcasting/restream",
            "broadcasting/zoom",
            "broadcasting/ffmpeg",
            "broadcasting/hardware",
            "broadcasting/jitsi",
          ],
        },
        "video",
        "storage",
        "latency",
        "metrics",
      ],
    },
    {
      type: "category",
      label: "Chat",
      link: { type: "doc", id: "chat/index" },
      items: [
        "chat/chat-authentication",
        "chat/emoji",
        "chat/moderation",
      ],
    },
    {
      type: "category",
      label: "Increase social reach and engagement",
      link: { type: "doc", id: "social/index" },
      items: [
        "social/the-fediverse",
        "social/featured-streams",
      ],
    },
    {
      type: "category",
      label: "Plugins, APIs, webhooks & your custom functionality",
      link: { type: "doc", id: "extend" },
      items: [
        {
          type: "category",
          label: "Web APIs",
          link: { type: "doc", id: "api/index" },
          items: [
            "api/requests",
            "api/webhooks",
            {
              type: "category",
              label: "API Reference",
              items: [
                {
                  type: "link",
                  label: "In development API documentation",
                  href: "/api/development",
                },
                {
                  type: "link",
                  label: "Released API documentation",
                  href: "/api/release",
                },
              ],
            },
          ],
        },
        "api/activitypub",
        {
          type: "category",
          label: "Owncast plugins",
          link: { type: "doc", id: "plugins/index" },
          items: [
            {
              type: "category",
              label: "Get started",
              key: "plugins-get-started",
              items: [
                "plugins/quickstart",
                {
                  type: "autogenerated",
                  dirName: "plugins/sdks",
                },
              ],
            },
            {
              type: "category",
              label: "Build features",
              items: [
                "plugins/chat",
                "plugins/commands",
                "plugins/configuration",
                "plugins/auth",
                "plugins/http",
                "plugins/ui",
              ],
            },
            {
              type: "category",
              label: "Reference",
              items: [
                "plugins/manifest",
                "plugins/events",
                "plugins/apis",
                "plugins/permissions",
              ],
            },
            {
              type: "category",
              label: "Ship & test",
              items: ["plugins/packaging", "plugins/testing"],
            },
          ],
        },
        "api/actions",
      ],
    },
    {
      type: "category",
      label: "Optional / Advanced Features & Maintenance",
      items: [
        {
          type: "category",
          label: "Add SSL & reverse proxies",
          link: { type: "doc", id: "sslproxies/index" },
          items: [
            "sslproxies/caddy",
            "sslproxies/haproxy",
            "sslproxies/lighttpd",
            "sslproxies/nginx",
            "sslproxies/apache",
          ],
        },
        "codecs",
        "cdns",
        "backups",
        "configuration/runtime-flags",
        "scaling",
        "viewers",
        "custom-assets",
      ],
    },
    {
      type: "category",
      label: "Watching Owncast Streams",
      link: { type: "doc", id: "watching-streams/watching-streams" },
      items: [
        "watching-streams/devices-amazon-fire-tv",
        "watching-streams/devices-apple-tv",
        "watching-streams/devices-chromecast",
        "watching-streams/devices-google-tv",
        "watching-streams/devices-iphone-ipad",
        "watching-streams/devices-kodi",
        "watching-streams/devices-lg-webos",
        "watching-streams/devices-roku",
        "watching-streams/devices-samsung-tv",
        "watching-streams/owncast-web",
      ],
    },
    "directory",
  ],
};

export default sidebars;
