import "survey-core/survey-core.css";
// SurveyJS UI strings (navigation, validation) for every locale, so adding a
// site language never requires touching this component
import "survey-core/survey.i18n";
import styles from "./Wizard.module.css";

import React, { JSX, useMemo } from "react";
import { translate } from "@docusaurus/Translate";
import useDocusaurusContext from "@docusaurus/useDocusaurusContext";
import { Model, Serializer, PageModel } from "survey-core";
import { Survey } from "survey-react-ui";

const { visitStrings } = require("../data/wizardStrings");

// Extend TypeScript interface for PageModel
declare module "survey-core" {
  interface PageModel {
    redirect?: string;
  }
}

// Extend the PageModel to support custom 'redirect' property
Serializer.addProperty("page", {
  name: "redirect:string",
  default: "",
});

interface AnalyticsEvent {
  eventName: string;
  questionName: string;
}

interface WizardProps {
  /** Raw survey tree JSON (English source strings) */
  tree: object;
  /** Stable wizard name; translation ids are `wizard.<name>.<path>` */
  name: string;
  /** Optional event emitted when this wizard's named question changes. */
  analyticsEvent?: AnalyticsEvent;
}

type Plausible = ((eventName: string) => void) & {
  q?: [string][];
};

declare global {
  interface Window {
    plausible?: Plausible;
  }
}

function trackPlausibleEvent(eventName: string): void {
  let plausible = window.plausible;
  if (!plausible) {
    const q: [string][] = [];
    plausible = Object.assign((event: string) => q.push([event]), { q });
    window.plausible = plausible;
  }
  plausible(eventName);
}

/**
 * Replaces every localizable tree string with its translation for the active
 * locale, looked up from the site's code.json via the standard Docusaurus
 * translation workflow. Untranslated strings fall back to English.
 * Source entries are generated by scripts/extract-wizard-strings.js.
 */
function localizeTree(tree: object, name: string): object {
  const clone = structuredClone(tree);
  visitStrings(
    clone,
    `wizard.${name}`,
    (id: string, message: string, node: Record<string, string>, key: string) => {
      node[key] = translate({ id, message });
    }
  );
  return clone;
}

export default function Wizard({
  tree,
  name,
  analyticsEvent,
}: WizardProps): JSX.Element {
  const { i18n } = useDocusaurusContext();
  const model = useMemo(() => {
    const m = new Model(localizeTree(tree, name));
    // SurveyJS chrome (buttons, validation messages) follows the site locale
    m.locale = i18n.currentLocale;
    m.showProgressBar = "off";
    if (analyticsEvent) {
      m.onValueChanged.add((_, options) => {
        if (options.name === analyticsEvent.questionName) {
          trackPlausibleEvent(analyticsEvent.eventName);
        }
      });
    }
    m.onCurrentPageChanged.add((sender, options) => {
      const redirect = options.newCurrentPage?.redirect;
      if (redirect) {
        // Tree redirects are default-locale paths; keep the reader's language
        const localized =
          i18n.currentLocale === i18n.defaultLocale || !redirect.startsWith("/")
            ? redirect
            : `/${i18n.currentLocale}${redirect}`;
        window.location.replace(localized);
      }
    });
    return m;
  }, [tree, name, i18n.currentLocale, analyticsEvent]);

  return (
    <div className={styles.wizard}>
      <Survey model={model} />
    </div>
  );
}
