#!/usr/bin/env node

/*
 * news-fallback
 *
 * The Owncast server admin pulls in news from the JSON feed produced by the
 * `content/news` section of this site. When every news post is a draft (or
 * there are none at all) that feed is empty and server operators see nothing.
 *
 * This pre-build script makes sure there's always something to show. If there
 * are no published news posts it fetches the most recent entry from the Owncast
 * newsletter (https://owncast.ghost.io/), converts it from HTML to Markdown, and
 * writes it out as a published news post.
 *
 * It is intentionally non-fatal: any network or parsing problem is logged and
 * the script exits 0 so it can never break a deploy.
 */

const fs = require("fs");
const path = require("path");
const https = require("https");
const matter = require("gray-matter");
const TurndownService = require("turndown");

const NEWS_DIR = path.join(__dirname, "..", "..", "content", "news");
const NEWSLETTER_RSS = "https://owncast.ghost.io/rss/";

// Front matter key we stamp on posts this script generates so they're easy to
// identify (and so a human-authored post is always preferred over ours).
const AUTOGEN_KEY = "autogenerated";

function log(...args) {
  console.log("[news-fallback]", ...args);
}

// Fetch a URL following redirects, resolving to the response body as a string.
function fetchText(url, redirects = 5) {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { "User-Agent": "owncast-news-fallback" } }, (res) => {
        const { statusCode, headers } = res;
        if (statusCode >= 300 && statusCode < 400 && headers.location) {
          if (redirects <= 0) {
            reject(new Error("too many redirects"));
            return;
          }
          res.resume();
          const next = new URL(headers.location, url).toString();
          resolve(fetchText(next, redirects - 1));
          return;
        }
        if (statusCode !== 200) {
          reject(new Error(`request to ${url} failed: HTTP ${statusCode}`));
          res.resume();
          return;
        }
        let body = "";
        res.setEncoding("utf8");
        res.on("data", (chunk) => (body += chunk));
        res.on("end", () => resolve(body));
      })
      .on("error", reject);
  });
}

// Returns true if the news section already has at least one live post: a file
// that isn't a draft and isn't dated in the future (Hugo hides future-dated
// content from builds by default, so it wouldn't reach the feed either).
function hasPublishedNews() {
  let files;
  try {
    files = fs.readdirSync(NEWS_DIR);
  } catch (err) {
    log(`could not read ${NEWS_DIR}:`, err.message);
    return false;
  }

  const now = Date.now();
  return files.some((file) => {
    if (!file.endsWith(".md") || file === "_index.md") return false;
    try {
      const { data } = matter.read(path.join(NEWS_DIR, file));
      if (data.draft) return false;
      if (data.date && new Date(data.date).getTime() > now) return false;
      return true;
    } catch (err) {
      log(`skipping unparseable ${file}:`, err.message);
      return false;
    }
  });
}

// Pull the named field out of a single RSS <item> block, handling both CDATA
// and plain-text values.
function extractField(itemXml, field) {
  const re = new RegExp(
    `<${field}(?:\\s[^>]*)?>\\s*(?:<!\\[CDATA\\[([\\s\\S]*?)\\]\\]>|([\\s\\S]*?))\\s*</${field}>`,
    "i"
  );
  const match = itemXml.match(re);
  if (!match) return "";
  return (match[1] !== undefined ? match[1] : match[2] || "").trim();
}

// Parse the first <item> out of the newsletter RSS feed.
function parseLatestItem(xml) {
  const itemMatch = xml.match(/<item>([\s\S]*?)<\/item>/i);
  if (!itemMatch) throw new Error("no <item> found in feed");
  const itemXml = itemMatch[1];

  const html = extractField(itemXml, "content:encoded");
  if (!html) throw new Error("newsletter entry has no content");

  return {
    title: extractField(itemXml, "title"),
    link: extractField(itemXml, "link"),
    author: extractField(itemXml, "dc:creator"),
    pubDate: extractField(itemXml, "pubDate"),
    description: extractField(itemXml, "description"),
    html,
  };
}

// Derive a filename slug from the newsletter's permalink, falling back to the
// title if needed.
function slugFor(item) {
  try {
    const parts = new URL(item.link).pathname.split("/").filter(Boolean);
    if (parts.length) return parts[parts.length - 1];
  } catch (_) {
    /* fall through */
  }
  return item.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Strip HTML tags and collapse whitespace for use in the description field.
function plainText(html) {
  return html
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&apos;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

function buildPost(item) {
  const turndown = new TurndownService({
    headingStyle: "atx",
    codeBlockStyle: "fenced",
    bulletListMarker: "-",
  });
  const body = turndown.turndown(item.html);

  const date = item.pubDate ? new Date(item.pubDate) : null;
  const dateStr =
    date && !Number.isNaN(date.getTime())
      ? date.toISOString()
      : new Date().toISOString();

  const description =
    plainText(item.description || item.html).slice(0, 160) || item.title;

  const byline =
    item.author && date
      ? `By [${item.author}](${item.link}) --- ${date.toLocaleDateString("en-US", {
          year: "numeric",
          month: "long",
          day: "numeric",
          timeZone: "UTC",
        })}\n\n`
      : "";

  const frontMatter = matter.stringify("", {
    title: item.title,
    source: item.link,
    date: dateStr,
    description,
    draft: false,
    [AUTOGEN_KEY]: true,
  });

  const intro =
    `This is the most recent copy of the Owncast community newsletter, ` +
    `originally published at [owncast.ghost.io](${item.link}). ` +
    `Subscribe to get it in your inbox [here](/newsletter).\n\n`;

  return `${frontMatter}\n${intro}${byline}${body}\n`;
}

async function run() {
  if (hasPublishedNews()) {
    log("published news already exists, nothing to do.");
    return;
  }

  log("no published news found, generating a post from the newsletter…");
  const xml = await fetchText(NEWSLETTER_RSS);
  const item = parseLatestItem(xml);
  const slug = slugFor(item);
  const outPath = path.join(NEWS_DIR, `${slug}.md`);

  if (fs.existsSync(outPath)) {
    log(`post already exists at ${path.basename(outPath)}, leaving it alone.`);
    return;
  }

  fs.writeFileSync(outPath, buildPost(item), "utf8");
  log(`wrote ${path.relative(path.join(__dirname, "..", ".."), outPath)} from "${item.title}".`);
}

run().catch((err) => {
  // Never fail the build over this.
  log("skipped:", err.message);
  process.exit(0);
});
