name: Bundle component library + style guide into web site

on:
  repository_dispatch:
    types: [bundle-components-library]

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Bundle Storybook
      run: ./scripts/bundleComponentGuide.sh

    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Owncast
        author_email: owncast@owncast.online
        message: "Update component library and style guide"
        add: "static/components"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.2'
        extended: true

    - name: Build
      run: npm install && hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  