name: Generate install preview video
on:
  push:
    paths:
      - "static/install.sh"
  workflow_dispatch:

jobs:
  generate-install-video:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate
        run: scripts/install-video-generator/generate-quickstart.sh

      - name: Commit changes
        run: |
          git config user.name "Owncast"
          git config user.email "owncast@owncast.online"
          git add static/install-preview.*
          git diff --staged --quiet || git commit -m "Update install preview video"
          git pull --rebase
          git push
